import { useState } from "react";
import {
  AnalysisData,
  RisksResult,
  SimplifyResult,
  ChecklistResult,
  Severity,
} from "@/types";

interface AnalysisResultProps {
  documentId: string;
  documentContent?: string;
  analysisType: "simplify" | "risks" | "checklist";
}

const SEVERITY_STYLES: Record<Severity, { badge: string; border: string; indicator: string }> = {
  high: {
    badge: "bg-rose-100 text-rose-800 dark:bg-rose-950/60 dark:text-rose-300 border-rose-300 dark:border-rose-800",
    border: "border-l-rose-500",
    indicator: "bg-rose-500",
  },
  medium: {
    badge: "bg-amber-100 text-amber-800 dark:bg-amber-950/60 dark:text-amber-300 border-amber-300 dark:border-amber-800",
    border: "border-l-amber-500",
    indicator: "bg-amber-500",
  },
  low: {
    badge: "bg-emerald-100 text-emerald-800 dark:bg-emerald-950/60 dark:text-emerald-300 border-emerald-300 dark:border-emerald-800",
    border: "border-l-emerald-500",
    indicator: "bg-emerald-500",
  },
};

function isSimplifyResult(data: AnalysisData): data is SimplifyResult {
  return typeof (data as SimplifyResult).summary === "string" && Array.isArray((data as SimplifyResult).keyPoints);
}

function isRisksResult(data: AnalysisData): data is RisksResult {
  return Array.isArray((data as RisksResult).risks) || Array.isArray((data as RisksResult).obligations);
}

function isChecklistResult(data: AnalysisData): data is ChecklistResult {
  return Array.isArray((data as ChecklistResult).actionItems) || Array.isArray((data as ChecklistResult).questionsForLawyer);
}

function isRawFallback(data: AnalysisData): data is { raw: string } {
  return typeof (data as { raw: string }).raw === "string";
}

export default function AnalysisResult({ documentId, documentContent, analysisType }: AnalysisResultProps) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [data, setData] = useState<AnalysisData | null>(null);
  const [copied, setCopied] = useState(false);
  const [completedTasks, setCompletedTasks] = useState<Record<number, boolean>>({});
  const [isCached, setIsCached] = useState(false);

  async function runAnalysis(): Promise<void> {
    if (loading) return; // Prevent duplicate concurrent requests
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ documentId, documentContent, analysisType }),
      });
      const body = await res.json();
      if (!res.ok || !body.success) {
        throw new Error(body.error || "Analysis failed");
      }
      setData(body.data as AnalysisData);
      setIsCached(!!body.cached);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Analysis failed");
    } finally {
      setLoading(false);
    }
  }

  function generateMarkdownReport(): string {
    if (!data) return "";
    let report = `# Legal Document Analysis Report\n`;
    report += `**Generated by**: Legal AI Assistant (Google Gemini 2.5)\n`;
    report += `**Notice**: Informational only — not legal advice.\n\n`;

    if (isSimplifyResult(data)) {
      report += `## Executive Summary\n${data.summary}\n\n`;
      report += `## Key Points\n`;
      data.keyPoints?.forEach((point) => {
        report += `- ${point}\n`;
      });
      report += `\n## Defined Terms Glossary\n`;
      Object.entries(data.termsDefinitions || {}).forEach(([term, def]) => {
        report += `- **${term}**: ${def}\n`;
      });
    } else if (isRisksResult(data)) {
      report += `## Risk Assessment: ${data.overallRiskLevel ? data.overallRiskLevel.toUpperCase() : "EVALUATED"}\n\n`;
      report += `### High-Priority Risks & Red Flags\n`;
      data.risks?.forEach((r) => {
        report += `- [${r.severity.toUpperCase()}] ${r.item}\n`;
      });
      report += `\n### Key Obligations\n`;
      data.obligations?.forEach((o) => {
        report += `- [${o.severity.toUpperCase()}] ${o.item}\n`;
      });
      report += `\n### Ambiguities & Open Clauses\n`;
      data.ambiguities?.forEach((a) => {
        report += `- ${a}\n`;
      });
    } else if (isChecklistResult(data)) {
      report += `## Action Plan & Preparation Summary\n${data.summary}\n\n`;
      report += `### Immediate Action Checklist\n`;
      data.actionItems?.forEach((item) => {
        report += `- [ ] [${item.priority.toUpperCase()}] ${item.task} ${item.deadlineOrTrigger ? `(${item.deadlineOrTrigger})` : ""}\n`;
      });
      report += `\n### Critical Questions for Legal Counsel\n`;
      data.questionsForLawyer?.forEach((q, idx) => {
        report += `${idx + 1}. **${q.question}**\n   - Context: ${q.contextOrClause}\n`;
      });
      report += `\n### Strategic Options & Next Steps\n`;
      data.userOptions?.forEach((opt) => {
        report += `#### Option: ${opt.option}\n`;
        report += `- **Pros**: ${opt.pros}\n`;
        report += `- **Cons**: ${opt.cons}\n\n`;
      });
    } else if (isRawFallback(data)) {
      report += `## Raw Output\n\`\`\`\n${data.raw}\n\`\`\`\n`;
    }

    return report;
  }

  function handleCopy(): void {
    const report = generateMarkdownReport();
    if (!report) return;
    navigator.clipboard.writeText(report).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  }

  function handleExportMarkdown(): void {
    const report = generateMarkdownReport();
    if (!report) return;
    const blob = new Blob([report], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `legal-${analysisType}-report.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  const typeLabels: Record<string, string> = {
    simplify: "Plain-English Simplification",
    risks: "Risk & Obligation Audit",
    checklist: "Action Checklist & Lawyer Prep",
  };

  return (
    <div className="space-y-5">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100">
              {typeLabels[analysisType]}
            </h2>
            {isCached && (
              <span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2 py-0.5 text-[10px] font-semibold text-emerald-700 dark:bg-emerald-950/60 dark:text-emerald-300 border border-emerald-200 dark:border-emerald-800">
                ⚡ Instant Cache Hit (&lt;5ms)
              </span>
            )}
          </div>
          <p className="text-xs text-slate-500 dark:text-slate-400">
            Automated analysis powered by Google Gemini 2.5 Flash
          </p>
        </div>
        <button
          type="button"
          onClick={() => void runAnalysis()}
          disabled={loading}
          aria-busy={loading}
          className="inline-flex items-center gap-2 rounded-lg bg-brand-600 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-brand-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-600 disabled:opacity-50"
        >
          {loading ? (
            <>
              <svg className="h-4 w-4 animate-spin text-white" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
              </svg>
              <span>Analyzing with Gemini...</span>
            </>
          ) : (
            `Run ${analysisType === "simplify" ? "Simplification" : analysisType === "risks" ? "Risk Audit" : "Preparation Plan"}`
          )}
        </button>
      </div>

      {error && (
        <div role="alert" className="rounded-lg border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800 dark:border-rose-900 dark:bg-rose-950/40 dark:text-rose-200">
          <p className="font-semibold">Analysis Failed</p>
          <p className="text-xs mt-1">{error}</p>
        </div>
      )}

      <div aria-live="polite">
        {/* SIMPLIFY RESULT */}
        {data && isSimplifyResult(data) && (
          <div className="space-y-4">
            <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
              <div className="mb-2 flex items-center gap-2">
                <span className="flex h-6 w-6 items-center justify-center rounded-full bg-brand-100 text-brand-700 text-xs font-bold dark:bg-brand-950 dark:text-brand-300">
                  1
                </span>
                <h3 className="font-semibold text-slate-900 dark:text-slate-100">Executive Plain-English Summary</h3>
              </div>
              <p className="text-sm leading-relaxed text-slate-700 dark:text-slate-300">{data.summary}</p>
            </div>

            <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
              <div className="mb-3 flex items-center gap-2">
                <span className="flex h-6 w-6 items-center justify-center rounded-full bg-brand-100 text-brand-700 text-xs font-bold dark:bg-brand-950 dark:text-brand-300">
                  2
                </span>
                <h3 className="font-semibold text-slate-900 dark:text-slate-100">Key Takeaways & What You Agree To</h3>
              </div>
              <ul className="space-y-2">
                {data.keyPoints?.map((point, i) => (
                  <li key={i} className="flex items-start gap-2.5 text-sm text-slate-700 dark:text-slate-300">
                    <svg className="h-5 w-5 shrink-0 text-emerald-500" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>
                    <span>{point}</span>
                  </li>
                ))}
              </ul>
            </div>

            {data.termsDefinitions && Object.keys(data.termsDefinitions).length > 0 && (
              <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
                <div className="mb-3 flex items-center gap-2">
                  <span className="flex h-6 w-6 items-center justify-center rounded-full bg-brand-100 text-brand-700 text-xs font-bold dark:bg-brand-950 dark:text-brand-300">
                    3
                  </span>
                  <h3 className="font-semibold text-slate-900 dark:text-slate-100">Jargon Decoded (Defined Terms)</h3>
                </div>
                <dl className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                  {Object.entries(data.termsDefinitions).map(([term, def]) => (
                    <div key={term} className="rounded-lg border border-slate-100 bg-slate-50 p-3 dark:border-slate-800 dark:bg-slate-800/50">
                      <dt className="text-xs font-bold uppercase tracking-wider text-brand-700 dark:text-brand-400">
                        {term}
                      </dt>
                      <dd className="mt-1 text-xs text-slate-600 dark:text-slate-300">{def}</dd>
                    </div>
                  ))}
                </dl>
              </div>
            )}
          </div>
        )}

        {/* RISKS RESULT */}
        {data && isRisksResult(data) && (
          <div className="space-y-4">
            {data.overallRiskLevel && (
              <div className="flex items-center justify-between rounded-xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900">
                <div>
                  <span className="text-xs font-semibold uppercase tracking-wider text-slate-500">Overall Risk Level</span>
                  <div className="flex items-center gap-2 mt-0.5">
                    <span className={`inline-block h-3 w-3 rounded-full ${SEVERITY_STYLES[data.overallRiskLevel].indicator}`} />
                    <span className="text-base font-bold capitalize text-slate-900 dark:text-slate-100">
                      {data.overallRiskLevel} Risk Contract
                    </span>
                  </div>
                </div>
                <span className={`rounded-full border px-3 py-1 text-xs font-bold uppercase tracking-wider ${SEVERITY_STYLES[data.overallRiskLevel].badge}`}>
                  {data.overallRiskLevel}
                </span>
              </div>
            )}

            <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
              <RiskSection title="Red Flags & Potential Risks" items={data.risks} icon="alert" />
              <RiskSection title="Your Key Obligations" items={data.obligations} icon="check" />
            </div>

            {data.ambiguities && data.ambiguities.length > 0 && (
              <div className="rounded-xl border border-amber-200 bg-amber-50/50 p-5 shadow-sm dark:border-amber-900/50 dark:bg-amber-950/20">
                <h3 className="mb-2 text-sm font-bold text-amber-900 dark:text-amber-200">
                  Ambiguous Clauses & Loopholes
                </h3>
                <p className="mb-3 text-xs text-amber-800/80 dark:text-amber-300/80">
                  These clauses use vague language that could lead to dispute or disadvantage:
                </p>
                <ul className="space-y-2">
                  {data.ambiguities.map((a, i) => (
                    <li key={i} className="flex items-start gap-2 text-xs text-amber-900 dark:text-amber-200">
                      <span className="font-bold text-amber-600 dark:text-amber-400">•</span>
                      <span>{a}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        )}

        {/* CHECKLIST RESULT (NEW: Alignment with Actionable Outputs & Lawyer Prep) */}
        {data && isChecklistResult(data) && (
          <div className="space-y-4">
            <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
              <h3 className="text-sm font-bold uppercase tracking-wider text-brand-700 dark:text-brand-400">
                Executive Action Summary
              </h3>
              <p className="mt-1 text-sm text-slate-700 dark:text-slate-300 leading-relaxed">{data.summary}</p>
            </div>

            {/* Interactive Action Checklist */}
            <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
              <div className="mb-3 flex items-center justify-between">
                <div>
                  <h3 className="font-semibold text-slate-900 dark:text-slate-100">
                    Immediate Action Checklist
                  </h3>
                  <p className="text-xs text-slate-500">Tick off items as you review and prepare:</p>
                </div>
                <span className="text-xs font-medium text-slate-500">
                  {Object.values(completedTasks).filter(Boolean).length} / {data.actionItems?.length || 0} completed
                </span>
              </div>

              <div className="space-y-2.5">
                {data.actionItems?.map((item, idx) => (
                  <label
                    key={idx}
                    className={`flex items-start gap-3 rounded-lg border p-3 transition cursor-pointer ${
                      completedTasks[idx]
                        ? "border-emerald-200 bg-emerald-50/50 dark:border-emerald-900/40 dark:bg-emerald-950/20"
                        : "border-slate-100 bg-slate-50 hover:bg-slate-100/70 dark:border-slate-800 dark:bg-slate-800/40"
                    }`}
                  >
                    <input
                      type="checkbox"
                      checked={!!completedTasks[idx]}
                      onChange={(e) => setCompletedTasks({ ...completedTasks, [idx]: e.target.checked })}
                      className="mt-0.5 h-4 w-4 rounded border-slate-300 text-brand-600 focus:ring-brand-500"
                    />
                    <div className="flex-1 text-xs">
                      <div className="flex items-center gap-2">
                        <span className={`font-medium ${completedTasks[idx] ? "line-through text-slate-400" : "text-slate-900 dark:text-slate-100"}`}>
                          {item.task}
                        </span>
                        <span className={`rounded border px-1.5 py-0.2 text-[10px] font-semibold uppercase ${SEVERITY_STYLES[item.priority].badge}`}>
                          {item.priority}
                        </span>
                      </div>
                      {item.deadlineOrTrigger && (
                        <p className="mt-0.5 text-slate-500 dark:text-slate-400">Trigger: {item.deadlineOrTrigger}</p>
                      )}
                    </div>
                  </label>
                ))}
              </div>
            </div>

            {/* Questions for Legal Professional */}
            <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
              <h3 className="font-semibold text-slate-900 dark:text-slate-100">
                Critical Questions to Ask Your Lawyer
              </h3>
              <p className="mb-3 text-xs text-slate-500">
                Armed with these tailored questions, your consultation will be focused and cost-effective:
              </p>
              <div className="space-y-3">
                {data.questionsForLawyer?.map((q, idx) => (
                  <div key={idx} className="rounded-lg border border-slate-100 bg-slate-50 p-3 dark:border-slate-800 dark:bg-slate-800/40">
                    <p className="text-xs font-semibold text-slate-900 dark:text-slate-100">
                      Q{idx + 1}: &ldquo;{q.question}&rdquo;
                    </p>
                    <p className="mt-1 text-[11px] text-slate-500 dark:text-slate-400">
                      <strong>Context:</strong> {q.contextOrClause}
                    </p>
                  </div>
                ))}
              </div>
            </div>

            {/* Strategic Options & Next Steps */}
            {data.userOptions && data.userOptions.length > 0 && (
              <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
                <h3 className="font-semibold text-slate-900 dark:text-slate-100 mb-1">
                  Strategic Options & Tradeoffs
                </h3>
                <p className="mb-3 text-xs text-slate-500">
                  Potential paths forward before signing or executing this agreement:
                </p>
                <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                  {data.userOptions.map((opt, idx) => (
                    <div key={idx} className="rounded-lg border border-slate-100 bg-slate-50 p-3.5 dark:border-slate-800 dark:bg-slate-800/40">
                      <p className="text-xs font-bold text-slate-900 dark:text-slate-100">{opt.option}</p>
                      <div className="mt-2 space-y-1 text-[11px]">
                        <p className="text-emerald-700 dark:text-emerald-400">
                          <strong>Pros:</strong> {opt.pros}
                        </p>
                        <p className="text-rose-700 dark:text-rose-400">
                          <strong>Cons:</strong> {opt.cons}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}

        {/* RAW FALLBACK */}
        {data && isRawFallback(data) && (
          <div className="rounded-lg border border-amber-200 bg-amber-50 p-4">
            <p className="text-sm text-amber-800 font-semibold">Gemini Response</p>
            <pre className="mt-2 whitespace-pre-wrap text-xs text-gray-700 font-mono">{data.raw}</pre>
          </div>
        )}
      </div>

      {data && (
        <div className="flex flex-wrap items-center gap-3 pt-2">
          <button
            type="button"
            onClick={handleExportMarkdown}
            className="inline-flex items-center gap-1.5 rounded-lg border border-slate-300 bg-white px-3.5 py-1.5 text-xs font-semibold text-slate-700 shadow-sm transition hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200 dark:hover:bg-slate-700"
          >
            <svg className="h-4 w-4 text-slate-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Download Markdown Report
          </button>
          <button
            type="button"
            onClick={handleCopy}
            className="inline-flex items-center gap-1.5 rounded-lg border border-slate-300 bg-white px-3.5 py-1.5 text-xs font-semibold text-slate-700 shadow-sm transition hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200 dark:hover:bg-slate-700"
          >
            {copied ? (
              <>
                <svg className="h-4 w-4 text-emerald-600" viewBox="0 0 20 20" fill="currentColor">
                  <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                </svg>
                <span className="text-emerald-700">Copied to Clipboard!</span>
              </>
            ) : (
              <>
                <svg className="h-4 w-4 text-slate-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" />
                </svg>
                <span>Copy Report</span>
              </>
            )}
          </button>
        </div>
      )}
    </div>
  );
}

function RiskSection({
  title,
  items,
  icon,
}: {
  title: string;
  items: { item: string; severity: Severity }[];
  icon: "alert" | "check";
}) {
  return (
    <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
      <h3 className="mb-3 font-semibold text-slate-900 dark:text-slate-100 flex items-center gap-2">
        {icon === "alert" ? (
          <span className="h-2 w-2 rounded-full bg-rose-500" />
        ) : (
          <span className="h-2 w-2 rounded-full bg-brand-500" />
        )}
        {title}
      </h3>
      <ul className="space-y-2">
        {items?.map((entry, i) => (
          <li
            key={i}
            className={`flex items-start gap-2.5 rounded-lg border-l-4 p-2.5 text-xs text-slate-700 dark:text-slate-300 bg-slate-50/70 dark:bg-slate-800/40 ${SEVERITY_STYLES[entry.severity].border}`}
          >
            <span
              className={`shrink-0 rounded border px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-wider ${SEVERITY_STYLES[entry.severity].badge}`}
            >
              {entry.severity}
            </span>
            <span className="leading-snug">{entry.item}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}
