import { useState } from "react";
import DocumentUpload from "./DocumentUpload";
import { CompareResult } from "@/types";

interface ComparisonViewProps {
  documentId: string;
  documentContent?: string;
}

export default function ComparisonView({ documentId, documentContent }: ComparisonViewProps) {
  const [secondDoc, setSecondDoc] = useState<{ id: string; filename: string; content?: string } | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<CompareResult | null>(null);
  const [copied, setCopied] = useState(false);

  async function runCompare(): Promise<void> {
    if (!secondDoc) return;
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/compare", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          documentId1: documentId,
          documentContent1: documentContent,
          documentId2: secondDoc.id,
          documentContent2: secondDoc.content,
        }),
      });
      const body = await res.json();
      if (!res.ok || !body.success) {
        throw new Error(body.error || "Comparison failed");
      }
      setResult(body.data as CompareResult);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Comparison failed");
    } finally {
      setLoading(false);
    }
  }

  function generateMarkdown(): string {
    if (!result) return "";
    let md = `# Legal Document Comparison Report\n`;
    md += `**Generated by**: Legal AI Assistant (Gemini 2.5)\n`;
    md += `**Disclaimer**: Informational comparison only — not legal advice.\n\n`;
    md += `## Executive Summary\n${result.summary}\n\n`;
    md += `## Section-by-Section Differences\n\n`;
    result.differences?.forEach((d) => {
      md += `### ${d.section}\n`;
      md += `- **Original Document**: ${d.doc1}\n`;
      md += `- **Revised Document**: ${d.doc2}\n`;
      md += `- **Legal / Practical Impact**: ${d.impact}\n\n`;
    });
    return md;
  }

  function handleCopy(): void {
    const md = generateMarkdown();
    if (!md) return;
    navigator.clipboard.writeText(md).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  }

  function handleDownload(): void {
    const md = generateMarkdown();
    if (!md) return;
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "document-comparison-report.md";
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="space-y-5">
      <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <h2 className="text-base font-semibold text-slate-900 dark:text-slate-100 mb-1">
          Compare with a Counter-Proposal or Prior Version
        </h2>
        <p className="text-xs text-slate-500 dark:text-slate-400 mb-4">
          Upload or paste the second document to perform a section-by-section diff and legal impact analysis.
        </p>

        <DocumentUpload
          label="Upload a second document to compare against"
          onUploaded={(doc) => setSecondDoc(doc)}
        />
      </div>

      <div className="flex items-center justify-between">
        <button
          type="button"
          onClick={() => void runCompare()}
          disabled={!secondDoc || loading}
          aria-busy={loading}
          className="inline-flex items-center gap-2 rounded-lg bg-brand-600 px-5 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-brand-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-600 disabled:opacity-50"
        >
          {loading ? (
            <>
              <svg className="h-4 w-4 animate-spin text-white" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
              </svg>
              <span>Comparing with Gemini...</span>
            </>
          ) : (
            "Compare Documents"
          )}
        </button>

        {secondDoc && (
          <span className="text-xs text-slate-500">
            Document 2: <strong>{secondDoc.filename}</strong>
          </span>
        )}
      </div>

      {error && (
        <div role="alert" className="rounded-lg border border-rose-200 bg-rose-50 p-4 text-xs font-medium text-rose-800 dark:border-rose-900 dark:bg-rose-950/40 dark:text-rose-200">
          {error}
        </div>
      )}

      <div aria-live="polite">
        {result && (
          <div className="space-y-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
            <div>
              <h3 className="text-sm font-bold uppercase tracking-wider text-brand-700 dark:text-brand-400">
                Comparison Summary
              </h3>
              <p className="mt-1 text-sm text-slate-700 dark:text-slate-300 leading-relaxed">{result.summary}</p>
            </div>

            <div className="overflow-x-auto rounded-lg border border-slate-200 dark:border-slate-800">
              <table className="w-full min-w-[600px] text-left text-xs">
                <caption className="sr-only">Differences between the two uploaded documents</caption>
                <thead className="bg-slate-50 dark:bg-slate-800/60">
                  <tr className="border-b border-slate-200 text-[11px] font-bold uppercase tracking-wider text-slate-600 dark:border-slate-700 dark:text-slate-400">
                    <th scope="col" className="py-3 px-4">Section</th>
                    <th scope="col" className="py-3 px-4">Document 1 (Original)</th>
                    <th scope="col" className="py-3 px-4">Document 2 (Version)</th>
                    <th scope="col" className="py-3 px-4">Substantive Impact</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                  {result.differences?.map((d, i) => (
                    <tr key={i} className="align-top hover:bg-slate-50/50 dark:hover:bg-slate-800/30">
                      <td className="py-3 px-4 font-semibold text-slate-900 dark:text-slate-100">
                        {d.section}
                      </td>
                      <td className="py-3 px-4 text-slate-600 dark:text-slate-300 leading-relaxed">
                        {d.doc1}
                      </td>
                      <td className="py-3 px-4 text-slate-600 dark:text-slate-300 leading-relaxed">
                        {d.doc2}
                      </td>
                      <td className="py-3 px-4">
                        <span className="inline-block rounded-md bg-amber-50 px-2 py-1 text-[11px] font-medium text-amber-900 dark:bg-amber-950/40 dark:text-amber-200">
                          {d.impact}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            <div className="flex flex-wrap items-center gap-3 pt-2">
              <button
                type="button"
                onClick={handleDownload}
                className="inline-flex items-center gap-1.5 rounded-lg border border-slate-300 bg-white px-3.5 py-1.5 text-xs font-semibold text-slate-700 shadow-sm transition hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200 dark:hover:bg-slate-700"
              >
                Download Comparison Report
              </button>
              <button
                type="button"
                onClick={handleCopy}
                className="inline-flex items-center gap-1.5 rounded-lg border border-slate-300 bg-white px-3.5 py-1.5 text-xs font-semibold text-slate-700 shadow-sm transition hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200 dark:hover:bg-slate-700"
              >
                {copied ? "Copied!" : "Copy Report"}
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
